# Generated by Django 6.1.1 on 2026-09-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Homepage hero photograph.', null=True, upload_to='branding/'),
        ),
    ]
