# Generated by Django 6.1.1 on 2026-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Hospital building/exterior photograph used on the About sections.', null=True, upload_to='branding/'),
        ),
    ]
